### ISSUE TITLE
AttributeError: module 'em' has no attribute 'RAW_OPT'

### ISSUE THREAD

**Issue by ccw1003** [ros-simulation/gazebo_ros_pkgs#1519]
when I catkin build this ros package, I met the error:
AttributeError: module 'em' has no attribute 'RAW_OPT';
Does anyone know how to deal with this problem?Or anyone met this error before?
I will be very grateful if anyone can help me.
![Uploading 2023-12-12 20-31-11 的屏幕截图.png…]()

**Comment by standmit** [comment]
solution:
https://stackoverflow.com/a/77656642

**Comment by kamronkhakimov** [comment]
I solved it by:
`pip install empy=3.3.4`

**Comment by covelus** [comment]
I think I probably accidentally updated all packages, and broke it again, as new empy packages (4.1) miss that RAW_OPT attribute. 
I got the error "This environment is externally managed", and I fixed it through:
`pip3 uninstall empy --break-system-packages`
`pip3 install empy==3.3.4 --break-system-packages`

**Comment by priya050898** [comment]
problem is not resolved using pip install empy=3.3.4 
problem still exist
![Screenshot from 2024-07-25 17-08-41](https://github.com/user-attachments/assets/914c397e-87a7-4bae-9ce2-bfeccb4c013a)

**Comment by ssapsu** [comment]
deactivate your virtual env and
make clean
make distclean
try it again

**Comment by Coisni1127** [comment]
![image](https://github.com/user-attachments/assets/773d9978-df41-429d-8db6-7ed55c9434e4)
problem still exist

**Comment by proffalken** [comment]
I hit this issue earlier on today.

In your workspace, remove `build`, `install`, and `logs` directories (probably only needs `build`, but you may as well make it completely fresh!), then re-run `colcon build`.

This worked for me.

**Comment by robin271828** [comment]
> I solved it by: `pip install empy=3.3.4`

pip install empy==3.3.4
